name: Manuscript CI

on:
  push:
    paths:
      - '**.tex'
      - '**.py'
      - '.github/workflows/ci.yml'
      - 'Makefile'
  pull_request:
    paths:
      - '**.tex'
      - '**.py'
      - '.github/workflows/ci.yml'
      - 'Makefile'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Structural + Hygiene Checks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt || true

      - name: Run tests
        run: |
          python -m unittest discover -s tests -v


      - name: Build LaTeX (dry run)
        run: |
          sudo apt-get update && sudo apt-get install -y latexmk texlive-full
          latexmk -pdf -cd -interaction=nonstopmode -halt-on-error src/main.tex

      - name: Check LaTeX log
        run: |
          python scripts/check_latex_log.py
