name: LaTeX Build and Check

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Using the latest Ubuntu runner on GitHub Actions

    - name: Run make all
      run: make check  # Run your make check command
