name: Lean CI

on:
  push:
    paths:
      - 'lean/**'
  pull_request:
    paths:
      - 'lean/**'

jobs:
  build:
    name: Build Lean Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Lean
        uses: leanprover/lean-action@v1
        with:
          toolchain: stable

      - name: Display Lean version
        working-directory: lean
        run: |
          lean --version
          lake --version

      - name: Build with Lake
        working-directory: lean
        run: |
          lake build

      - name: Check for `sorry`
        working-directory: lean
        run: |
          if grep -rE '\bsorry\b' --include='*.lean' .; then
            echo "❌ 'sorry' found in Lean source files."
            exit 1
          else
            echo "✅ No 'sorry' found."
          fi
