name: Lean CI

on:
  push:
    paths:
      - '**.lean'
      - 'lean/lean-toolchain'
      - 'lean/lakefile.lean'
  pull_request:
    paths:
      - '**.lean'
      - 'lean/lean-toolchain'
      - 'lean/lakefile.lean'

jobs:
  build:
    name: Build Lean Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Elan (Lean version manager)
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Install Lake and Show Versions
        run: |
          lake --version
          lean --version
        working-directory: ./lean

      - name: Update dependencies
        run: lake update
        working-directory: ./lean

      - name: Build with Lake
        run: lake build
        working-directory: ./lean

      - name: Check for `sorry`
        run: |
          if grep -rE '\bsorry\b' --include='*.lean' .; then
            echo "❌ 'sorry' found in Lean source files."
            exit 1
          else
            echo "✅ No 'sorry' found."
          fi
        working-directory: ./lean
