name: Lean CI

on:
  push:
    paths:
      - '**.lean'
      - 'lean-toolchain'
      - 'lakefile.lean'
      - 'lake-manifest.json'
  pull_request:
    paths:
      - '**.lean'
      - 'lean-toolchain'
      - 'lakefile.lean'
      - 'lake-manifest.json'

jobs:
  build:
    name: Build Lean Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Lean (uses lean-toolchain)
        uses: leanprover/lean-action@v1

      - name: Show Lean version
        run: |
          lean --version
          lake --version

      - name: Build with Lake
        run: |
          lake build

      - name: Check for `sorry`
        run: |
          if grep -rE '\bsorry\b' --include='*.lean' .; then
            echo "❌ 'sorry' found in Lean source files."
            exit 1
          else
            echo "✅ No 'sorry' found."
          fi
